### PR TITLE
Update pt_poll_week1.tex

### PR DESCRIPTION
**Pull request by lingwei-kong**
Rephrase a bit to avoid confusion, and update two questions with more than one correct answer.

### CODE REVIEW

**Comment by ndvanforeest** [comment]
Please the abbreviations of the abbreviations.sty file, like \P for probabilities and the like. Also, we mostly write outcomes of experiments between dollars, like $HHH$.

**Comment by lingwei-kong** [comment]
Hi Nicky,

Polleverywhere only compiles very simple latex as it is website-based and
if we want to copy paste directly from the code file it might be easier to
avoid customized commands or math symbols just fot the quizzes part.

Best,
Lingwei

**Comment by ndvanforeest** [comment]
That is strange. I'll pass by, and let's see what happens.

**Comment by lingwei-kong** [comment]
Hi Nicky,

I think rock and I will explain that during the pilot today how
polleverywhere works and then it would be clear.

Best,
Lingwei

**Review by ndvanforeest — APPROVED** [review]

**Pull request merged**
